In [166]:
import numpy as np

Номер 1

In [167]:
print ( np.pad(np.zeros((8,8)), pad_width = 1, constant_values = 1) )

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Номер 2

In [168]:
print ( np.indices((8,8)).sum(axis=0) % 2 )
print ('\n')
print ( np.array(([1,0]*4+[0,1]*4)*4).reshape((8,-1)) )

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Номер 3

In [169]:
print ( np.fromfunction(lambda i, j: np.where((i*5 + j + 1) % 6 == 0, i % 5, 0), (5,5), dtype=int) )

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Номер 4

In [170]:
array = (array := np.random.rand(5, 5)) - np.mean(array, axis=1, keepdims=True)

print("Массив:\n", array, "\n\nПроверка среднего по строкам:")
print (np.where(array.mean(axis=1)<1e-13, 0, array.mean(axis=1)))

Массив:
 [[-0.02588348  0.09161475  0.28193715 -0.18685038 -0.16081804]
 [-0.34166486  0.01741622  0.34727555 -0.34665154  0.32362464]
 [-0.53213736 -0.01324176  0.25275483 -0.02292532  0.31554962]
 [ 0.45945905 -0.4794553  -0.02606529  0.01156459  0.03449695]
 [-0.05530842  0.50631279  0.05213573 -0.17239212 -0.33074798]] 

Проверка среднего по строкам:
[0. 0. 0. 0. 0.]


Номер 5

In [175]:
print ( np.sum((x := np.random.rand(10,3)) * np.eye(x.shape[1])[np.argmin(np.abs(x-0.5), axis=1)], axis = 1) )

"""
checker:

x = np.random.rand(10,3)
print(x)
print ( np.sum((x) * np.eye(x.shape[1])[np.argmin(np.abs(x-0.5), axis=1)], axis = 1) )
"""

[0.28604718 0.83670234 0.47450831 0.56301801 0.45352011 0.32901161
 0.51044902 0.42287582 0.42256205 0.46099186]


Номер 6

In [172]:
"""x = np.random.rand(6,6)
print(x)
mask = np.transpose(np.eye(x.shape[0])[np.argmax(x, axis=0)])
colmax = np.sum(x*mask, axis = 0)
np.sum(x, axis = 1)/colmax
"""
print(np.sum((x := np.random.rand(6,6)), axis = 1)/np.sum(x*np.transpose(np.eye(x.shape[0])[np.argmax(x, axis=0)]), axis = 0))

[4.6175976  3.13840572 5.11634294 3.27996456 4.44020239 2.25826259]


Номер 7

In [173]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print ( x[ np.where(x[:-1]==0)[0] + 1 ].max() )

5


Номер 8

In [174]:
x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])

print ( x + np.bincount(i, minlength=len(x)) )

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
